addons:
  apt:
    packages:
      - imagemagick

language: php

env:
  - PHAN_ALLOW_XDEBUG=0
  - PHAN_DISABLE_XDEBUG_WARN=1

matrix:
  include:
    - php: 7.4
#    - php: nightly
  allow_failures:
    - php: 7.4
#    - php: nightly

before_install:
  - pecl channel-update pecl.php.net
  - printf "\n" | pecl install imagick
  - pecl install ast

install: travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml
  - vendor/bin/phan

after_script: bash <(curl -s https://codecov.io/bash)
